import { EmployeeDocument } from '../types/employee-document';

export const MOCK_EMPLOYEE_DOCUMENTS: EmployeeDocument[] = [
  {
    id: 1,
    fullName: 'John Doe',
    salary: 50000,
    email: 'john@example.com',
    position: 'Developer',
    creationDate: new Date(),
  },
  {
    id: 2,
    fullName: 'Jane Smith',
    salary: 60000,
    email: 'jane@example.com',
    position: 'Manager',
    creationDate: new Date(),
  },
  {
    id: 3,
    fullName: 'Mike Johnson',
    salary: 45000,
    email: 'mike.johnson@example.com',
    position: 'QA',
    creationDate: new Date(),
  },
  {
    id: 4,
    fullName: 'Emily Davis',
    salary: 70000,
    email: 'emily.davis@example.com',
    position: 'Designer',
    creationDate: new Date(),
  },
  {
    id: 5,
    fullName: 'Chris Brown',
    salary: 55000,
    email: 'chris.brown@example.com',
    position: 'Developer',
    creationDate: new Date(),
  },
  {
    id: 6,
    fullName: 'Sara Wilson',
    salary: 48000,
    email: 'sara.wilson@example.com',
    position: 'QA',
    creationDate: new Date(),
  },
  {
    id: 7,
    fullName: 'David Lee',
    salary: 65000,
    email: 'david.lee@example.com',
    position: 'Manager',
    creationDate: new Date(),
  },
  {
    id: 8,
    fullName: 'Sophia Martinez',
    salary: 51000,
    email: 'sophia.martinez@example.com',
    position: 'Designer',
    creationDate: new Date(),
  },
  {
    id: 9,
    fullName: 'James Garcia',
    salary: 58000,
    email: 'james.garcia@example.com',
    position: 'Developer',
    creationDate: new Date(),
  },
  {
    id: 10,
    fullName: 'Olivia Rodriguez',
    salary: 50000,
    email: 'olivia.rodriguez@example.com',
    position: 'QA',
    creationDate: new Date(),
  },
  {
    id: 11,
    fullName: 'Liam Perez',
    salary: 52000,
    email: 'liam.perez@example.com',
    position: 'Manager',
    creationDate: new Date(),
  },
  {
    id: 12,
    fullName: 'Ava Harris',
    salary: 60000,
    email: 'ava.harris@example.com',
    position: 'Designer',
    creationDate: new Date(),
  },
  {
    id: 13,
    fullName: 'Ethan Clark',
    salary: 49000,
    email: 'ethan.clark@example.com',
    position: 'Developer',
    creationDate: new Date(),
  },
  {
    id: 14,
    fullName: 'Isabella Lewis',
    salary: 53000,
    email: 'isabella.lewis@example.com',
    position: 'QA',
    creationDate: new Date(),
  },
  {
    id: 15,
    fullName: 'Mason Walker',
    salary: 61000,
    email: 'mason.walker@example.com',
    position: 'Manager',
    creationDate: new Date(),
  },
];
